#ifndef IMAGE_DEFINES_H
#define IMAGE_DEFINES_H

#define IMAGE_COUNT 5

#define START_IMAGE 0
#define PRISON_IMAGE 1
#define PARKING_IMAGE 2
#define POLICEMAN_IMAGE 3
#define CHANCE_IMAGE 4

#endif //IMAGE_DEFINES_H
